/V,L,REAL(0)[0],0,VOLTAGE_PV
/V,L,REAL(0)[0],0,CURRENT_PV
/V,L,REAL(0)[0],0,INPUT_VOLTAGE_FEEDBACK
/V,L,REAL(0)[0],0,TEMPERATURE_MAX
/V,L,UINT(0)[0],0,MODE_NOW
/V,L,BOOL(0)[0],0,LOCAL_REMOTE_indictor
/V,L,BOOL(0)[0],0,SHUTDOWN_COMMON_FAULT
/V,L,BOOL(0)[0],0,FAULT_SHUTDOWN_bit1
/V,L,BOOL(0)[0],0,CURRENT_CONSTANT_bit2
/V,L,BOOL(0)[0],0,FAN_FAULT_bit3
/V,L,BOOL(0)[0],0,OVERVOLTAGE_INPUT_SD_bit4
/V,L,BOOL(0)[0],0,UNDERVOLTAGE_INPUT_SD_bit5
/V,L,BOOL(0)[0],0,OVERVOLTAGE_OUTPUT_SD_bit6
/V,L,BOOL(0)[0],0,UNDERVOLTAGE_OUTPUT_bit7
/V,L,BOOL(0)[0],0,OVERCURRENT_SHUTDOWN_byte7bit0
/V,L,BOOL(0)[0],0,OVERTEMPERATURE_SHUTDOWN_byte7bit1
/V,L,UINT(0)[0],0,CHARGE_INTERLOCK

