/V,L,REAL(0)[0],0,BMS_VOLTAGE
/V,L,REAL(0)[0],0,BMS_CURRENT
/V,L,REAL(0)[0],0,SOC
/V,L,REAL(0)[0],0,SOH
/V,L,REAL(0)[0],0,total_system_capacity
/V,L,REAL(0)[0],0,System_surplus_capacity
/V,L,REAL(0)[0],0,Maximum_charging_current
/V,L,REAL(0)[0],0,Maximum_discharging_current
/V,L,REAL(0)[0],0,Maximum_discharging_power
/V,L,REAL(0)[0],0,Maximum_charging_voltage
/V,L,REAL(0)[0],0,Minimum_discharge_voltage
/V,L,SINT(0)[0],0,Maximum_cell_temperature
/V,L,SINT(0)[0],0,Minimum_cell_temperature
/V,L,REAL(0)[0],0,Maximum_cell_voltage
/V,L,REAL(0)[0],0,Minimum_cell_voltage
/V,L,BitField_BYTE(0)[0],0,STATUS_RELAY
/V,L,USINT(0)[0],0,Heart_beat
/V,L,BitField_WORD(0)[0],0,FAULT_1_LEVEL
/V,L,BitField_WORD(0)[0],0,FAULT_2_LEVEL
/V,L,UINT(0)[0],0,FAULT_3_LEVEL_1
/V,L,REAL(0)[0],0,Cumulative_battery_running_time
/V,L,INT(0)[0],0,Battery_charging_power
/V,L,INT(0)[0],0,Remaining_battery_life
/V,L,INT(0)[0],0,Nominal_capacity_of_battery_pack
/V,L,INT(0)[0],0,Battery_discharge_power
/V,L,BYTE(0)[0],0,serial_parrll_status
/V,L,UINT(0)[0],0,FAULT_3_LEVEL_2

