/V,L,REAL(0)[0],0,INPUT_VOLTAGE
/V,L,REAL(0)[0],0,OUTPUT_VOLTAGE
/V,L,REAL(0)[0],0,OUTPUT_CURRENT
/V,L,USINT(0)[0],0,FAULT_CODE
/V,L,USINT(0)[0],0,TEMPERATURE
/V,L,USINT(0)[0],0,STATUS
/V,L,USINT(0)[0],0,HEART_BEAT
/V,L,USINT(0)[0],0,CTL_CMD

