/V,L,REAL(0)[0],0,POWER_LIMIT
/V,L,USINT(0)[0],0,DPU_WORK_STATUS
/V,L,USINT(0)[0],0,DPU_FAULT_STATUS
/V,L,USINT(0)[0],0,SYS_MODE
/V,L,USINT(0)[0],0,EM_STATUS
/V,L,USINT(0)[0],0,DPU_HEART_BEAT
/V,L,BitField_BYTE(0)[0],0,ESSA_WORK_STATUS
/V,L,USINT(0)[0],0,POD_LEVEL
/V,L,UINT(0)[0],0,POD_POWER
/V,L,UINT(0)[0],0,POD_SPEED
/V,L,USINT(0)[0],0,ESSA_HEART_BEAT
/V,L,REAL(0)[0],0,CTL_BAT_VOLT12v

